services:
  - type: web
    name: vishal-music-bot
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "3000"
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOGGER_ID
        sync: false
      - key: PRIMARY_API_URL
        value: https://api.shrutibots.site
      - key: VISHAL_API_KEY
        value: ShrutiBotsc7zkBuuYtyvKJas3omsr
